management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      enabled: true
    metrics:
      enabled: true
    beans:
      enabled: true
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true
    threaddump:
      enabled: true
