management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      enabled: true
    metrics:
      enabled: true
    beans:
      enabled: true
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true
    threaddump:
      enabled: true


application:
  number-of-floors: 5
  number-of-underground-floors: 0
  number-of-elevators: 5
  floor-passing-time: 5000
  socket:
    mapping: "/ws/lifts"
    refresh: 3000
